users:
  max_length_name: 50
  max_length_email: 255
  EMAIL_REGEX: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
  min_length_password: 8
  users_per_page: 6
  user_avatar_size: 50
  default_user_avatar_size: 80
  reset_expired: 2
microposts:
  resize_image: [500, 500]
  max_length_content: 140
  image_type: ['image/png', 'image/jpg', 'image/jpeg']
  image_size: 5
  image_type_accepted: "image/jpeg, image/gif, image/png"
